version: '3.8'

services:
  nextjs:
    build:
      context: ./
    container_name: nextjs_app
    restart: always
    # Do no expose the port to the host machine
    # ports:
    #   - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    networks:
      - app-network

  flask:
    build:
      context: ./api
    container_name: flask_api
    restart: always
    # Do not expose the port to the host machine
    # ports:
    #   - "5328:5328"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - nextjs
      - flask

networks:
  app-network:
    driver: bridge
